### ISSUE TITLE
debugging help needed:  Endless loop with Simple example. Problem with "isRelative" divert state coherancy?

### ISSUE THREAD

**Issue by Glidias** [Glidias/inkhaxe#1]
**General Question:**
 @joethephish, if you set up a new Story(jsonInput), but do not progress it further in anyway, and then immediately call myStory.ToJsonString() after that, should you get back the _exact_ same runnable JSON output as the input?

**answer: Ok, I ran the C# original runtime and called ToJsonString() after creating the Story. (apparently, inkjs's ToJsonString() might not be working..), For the C# original, it does return the EXACT output as the input json provided....so I'm missing something here in the haxe port, but what?**
_It looks like my objective is to ensure i get back the same exact JSON output as the input upon creation of Story._ , using the myStory.ToJsonString() method.

**The problem:**
I've got an endless loop problem with the current Haxe port i'm doing with a simple example Hello World file consisting of 1 Hello World statement and and single choice to select. If I call Continue() on the story, it'll cause an endless loop at the point where it approaches the Divert which is formed due to the `f()` choice. 

Somehow, (partly due to lazy instantation within "targetPath/path" getters??....), the Path targetPath is lazily instantiated and thus will have their "isRelative" variable set to false by default (and no followup action is done to re-validate isRelative to match with their component strings, it seems).

I don't encounter this hanging problems when running the JSON file under inkjs or the original C# runtime (however, I had problems using ToJsonString() with inkjs ). The test is currently done on the `index-demo.html` file at:  https://github.com/Glidias/inkhaxe/tree/master/bin   , using `simple.ink.json`.

Current situation:

JS code:

```
    myStory = new ink.runtime.Story(inkFile);
    console.log(myStory.ToJsonString());
```

Original JSON of inkFile (simple.ink.json):

```
{
    "inkVersion": 12,
    "root": [
        [{
            "->": "start"
        }, null], "done", {
            "start": [
                ["^Hello world", "\n", ["ev", "str", {
                    "f()": ".^.s"
                }, "/str", "/ev", {
                    "*": ".^.c",
                    "flg": 18
                }, {
                    "s": ["^Hut 14.", null],
                    "c": [{
                        "f()": ".^.^.s"
                    }, "\n", "^The door was locked after I sat down.", "\n", "end", {
                        "#f": 5
                    }]
                }], null], {
                    "#f": 3
                }
            ],
            "global decl": ["ev", 0, {
                "VAR=": "forceful"
            }, 0, {
                "VAR=": "evasive"
            }, 0, {
                "VAR=": "teacup"
            }, 0, {
                "VAR=": "gotcomponent"
            }, 0, {
                "VAR=": "drugged"
            }, 0, {
                "VAR=": "hooper_mentioned"
            }, 0, {
                "VAR=": "losttemper"
            }, 0, {
                "VAR=": "admitblackmail"
            }, 0, {
                "VAR=": "hooperClueType"
            }, 0, {
                "VAR=": "hooperConfessed"
            }, 0, {
                "VAR=": "smashingWindowItem"
            }, 0, {
                "VAR=": "notraitor"
            }, 0, {
                "VAR=": "revealedhooperasculprit"
            }, 0, {
                "VAR=": "smashedglass"
            }, 0, {
                "VAR=": "muddyshoes"
            }, 0, {
                "VAR=": "framedhooper"
            }, 0, {
                "VAR=": "putcomponentintent"
            }, 0, {
                "VAR=": "throwncomponentaway"
            }, 0, {
                "VAR=": "piecereturned"
            }, 0, {
                "VAR=": "longgrasshooperframe"
            }, 0, {
                "VAR=": "DEBUG"
            }, "/ev", "end", null],
            "#f": 3
        }
    ]
}
```

vs.

Re-Outputted JSON from console.log: (with slight differences described below...scroll down to bottom to see summarised diff)

```
{
    "inkVersion": 12,
    "root": [
        [{
            "->": "start"
        }, null], "done", {
            "start": [
                ["^Hello world", "\n", ["ev", "str", {
                    "f()": ".^"
                }, "/str", "/ev", {
                    "*": ".^.c",
                    "flg": 18
                }, {
                    "s": ["^Hut 14.", {
                        "#n": "s"
                    }],
                    "c": [{
                        "f()": ".^.^"
                    }, "\n", "^The door was locked after I sat down.", "\n", "end", {
                        "#f": 5,
                        "#n": "c"
                    }]
                }], null], {
                    "#f": 3,
                    "#n": "start"
                }
            ],
            "global decl": ["ev", 0, {
                "VAR=": "forceful"
            }, 0, {
                "VAR=": "evasive"
            }, 0, {
                "VAR=": "teacup"
            }, 0, {
                "VAR=": "gotcomponent"
            }, 0, {
                "VAR=": "drugged"
            }, 0, {
                "VAR=": "hooper_mentioned"
            }, 0, {
                "VAR=": "losttemper"
            }, 0, {
                "VAR=": "admitblackmail"
            }, 0, {
                "VAR=": "hooperClueType"
            }, 0, {
                "VAR=": "hooperConfessed"
            }, 0, {
                "VAR=": "smashingWindowItem"
            }, 0, {
                "VAR=": "notraitor"
            }, 0, {
                "VAR=": "revealedhooperasculprit"
            }, 0, {
                "VAR=": "smashedglass"
            }, 0, {
                "VAR=": "muddyshoes"
            }, 0, {
                "VAR=": "framedhooper"
            }, 0, {
                "VAR=": "putcomponentintent"
            }, 0, {
                "VAR=": "throwncomponentaway"
            }, 0, {
                "VAR=": "piecereturned"
            }, 0, {
                "VAR=": "longgrasshooperframe"
            }, 0, {
                "VAR=": "DEBUG"
            }, "/ev", "end", {
                "#n": "global decl"
            }],
            "#f": 3
        }
    ]
}
```

Differences:
Basically, everything is "okay" and matching for the re-outputted JSON...as the NULL variable uses the "#n" object which is similar just using null (issit? not too sure about this.). However, the main thing (showstopper) that causes an endless loop when using the re-outputted JSON for the new Story(), are the "f()" re-divert targetPath properties,  due the targetPaths being laziliy instantiated and not having the correct "isRelative" boolean state set accordingly in relation to it's compactedPathString......"or something else.."

.....Thus, you've got a Divert with relative targetPath that should return  a compacted target path value of `".^.s"` (as of the original JSON), but instead returns a targetPath value of `".^"` (with the re-outputted JSON). Somehow, this causes it to loop endlessly within the same branch, and refuses to exit!

 Hmm...Anyway to fix this? In summary, it appears that my relative f() targetPaths are being treated as global paths, (due to the isRelative property somehow set to false for those targetPaths when it shouldn't be the case...)  Are all "path.isRelative" properties implicitly being set upon lazy instantation of paths during "path" getter operations?? (bleh, sounds like a bad approach...)

**Comment by Glidias** [comment]
Ok, basically, I learnt that whether the path is global or relative, Object.getCompactedString() will always be responsible for getting a CONSISTENT version of the string regardless for JSON output.

Apparently, the tail() property was retrieved wrongly due to array.slice(..) using the wrong index (2nd) parameter. (because C#list.getRange() uses count of items, not index..)

Thus, this issue is considered resolved.

**Comment by y-lohse** [comment]
[Sounds familiar^^](https://github.com/y-lohse/inkjs/blob/master/engine/Path.js#L33)

**Comment by Glidias** [comment]
Ok, after checking off some typos, I'm able to get an advanced game example script (Trosink!) to work on InkHaxe! https://glidias.github.io/inkhaxe/  Just run the sample story..

But lol, the JS performance is rather slow when executing my game example (it has tons of data, loopbacks and calculations purely within Ink,...hmm..)  In fact, running it off the C# runtime on EdgeJS, is actually  faster..

Probably, complex RPG combat simulation systems aren't really meant to execute smoothly on Ink ...and it may be better to use externally executed functions instead?

What's left is to implement a macro/runtime method to set up the esX proxy public getters/setters for Story class under JS target. For now, it's kinda ugly to have to use the get_??(), set_???() methods.. but its workin.

**Comment by joethephish** [comment]
Yeah, ink definitely isn't built for execution speed - I'd definitely recommend more complex logic gets moved into the native language.

I'd be interested to see some basic benchmarks done in:
- ink's original C# runtime implementation as a baseline
- inkjs
- the Haxe port:
  - using various targets - especially interested to see what it's like when compiling via the C++ target!
