### ISSUE TITLE
Consistent crash on C++ targets

### ISSUE THREAD

**Issue by danhett** [Glidias/inkhaxe#10]
I'm attempting to use this library on a new large-scale OpenFL project, and while everything works great under Neko and my Ink story plays, I get an instant hard crash on both Windows and OSX that is definitely being caused by this library (including the updated forks from @sh-dave and others), I've tried everything). Obviously I know this lib has been somewhat dormant, so I'm not enormously surprised it's not perfect on newer versions of Haxe etc, but would really like to be able to use it in my app as I've built other stuff around it. 

Has anyone got this working on new Haxe versions etc? I don't get a stack trace or anything, so I'm unsure where to start, the application just crashes to desktop as soon as I create a new Story() on all cpp platforms.

Thanks!

**Comment by sh-dave** [comment]
I'm not quite sure if it's related to your issue, but can you check your json file encoding? I remember i had some issue with it being utf-8 with BOM, and converting to normal utf-8 solved it.

**Comment by danhett** [comment]
Ah, so actually this might be something. I wrote the Ink code a long while ago (during a prototype phase which carried over) and I'm doing `haxe.Utf8.decode` on the string before creating the Story object. In hindsight I'd be expecting to do the opposite of this. If I don't do this step, the Neko build also fails, but works with it in. The json files are being generated directly by the Inky editor and are definitely UTF-8 encoded. Any ideas?

**Comment by sh-dave** [comment]
Just round tripping via `haxe.Utf8.decode()` on the sample file https://github.com/Glidias/inkhaxe/blob/master/bin/tros.ink.json doesn't work for me. I have to actually save the file with a normal utf-8 encoding (using vscode, click on `UTF-8 with BOM` in the status bar and then `Save with Encoding` -> `UTF8`).

![Screenshot_2020-04-02_09-57-36](https://user-images.githubusercontent.com/13007175/78232264-45bb1a00-74d4-11ea-8b2d-d0ed7eb908a5.png)

**Comment by danhett** [comment]
Ahha! That is exactly it, my test works perfectly now on OSX, and I assume Windows but I'll check. Thanks so much for the assist, good catch! :)
