### ISSUE TITLE
What version of Ink is supported?

### ISSUE THREAD

**Issue by NQNStudios** [Glidias/inkhaxe#7]
I'm considering Haxe for my games, and having an available port of Ink is important for whatever platform I choose. I'm willing to contribute to an Ink port if it means getting to use the best/most portable language for my games.

So my first question is, how far did you get on porting Ink here? If the runtime you have here is complete for any version of Ink, which one would that be and how could we set a roadmap to get it up to date?

**Comment by sh-dave** [comment]
https://github.com/Glidias/inkhaxe/blob/33a54b88f9e14e459699e60b9947dc9a742a18ce/src/ink/runtime/Story.hx#L31 I tried setting it to `17` and it seemed to work for the most part (it's missing Tag, List and Random serialization). I also have a [WIP branch](https://github.com/Glidias/inkhaxe/network) with the start of some updates to it, but currently lack the time to finish it and clean it up. Maybe it's helpful to you though.
