### ISSUE TITLE
C++ Haxe target support

### ISSUE THREAD

**Issue by fire** [Glidias/inkhaxe#9]
Has anyone tried the C++ haxe target? The goal is for a native godot engine plugin for ink.

**Comment by Glidias** [comment]
Nope. 

This is 1 year old already, so I'd expect somewhat would have done a direct build for Godot.. (yup, eg. https://github.com/paulloz/godot-ink).

It would be nice if i could continue maintaining this, but I don't know where to start. Feel free to fork this project and make pull requests accordingly.
